<!DOCTYPE html>
<html lang="en" ng-app="redisApp">
<head>
    <meta charset="utf-8">
    <title>Fun with Redis 2.0</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="/css/flat-ui.css" rel="stylesheet">

    <link href="/css/style.css" rel="stylesheet">

    <link rel="shortcut icon" href="/images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <![endif]-->

    <script src="/js/angular.js"></script>
    <script src="/js/angular-route.js"></script>
    <script src="/js/angular-sanitize.js"></script>
</head>
<body class="palette-midnight-blue">
<header>
    <h3 class="palette palette-wet-asphalt">Fun with Redis 2.0</h3>
</header>
<div id="omni" style="">
    <div class="container">
        <div class="row">
            <div class="col col-sm-4">
                <div class="tile">
                    <h1 class="">{{status.requestsPerSecond}}</h1>
                    <h6>CMDs per Sec. (Max: {{status.requestsPerSecondMax}})</h6>
                </div>
            </div>
            <div class="col col-sm-4">
                <div class="tile">
                    <h1 class="">{{status.activeWorkers}}</h1>
                    <h6>Active / Total Workers</h6>
                </div>
            </div>
            <div class="col col-sm-4">
                <div class="tile">
                    <h1 class="">{{status.userCpu}}%</h1>
                    <h6>Redis CPU</h6>
                </div>
            </div>
        </div>
        <div class="row" style="padding:20px 0 0 0;">
            <div class="col-sm-2">
                <h6 style="text-align: right;">CPU:</h6>
            </div>
            <div class="col-sm-9" style="padding-top:10px;">
                <div class="progress">
                    <div id="userCpu" class="progress-bar" style="width: 0%;"></div>
                    <div id="sysCpu" class="progress-bar progress-bar-warning" style="width: 0%;"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div id="modeHtml" class="col col-sm-12" ng-bind-html="trustedHtml">

            </div>
        </div>
        <div id="MenuCtrl" class="row" style="padding: 20px 0 0 0;" ng-controller="MenuCtrl">
            <div class="col-md-12">
                <div class="navbar navbar-inverse">
                    <div class="navbar-collapse collapse" id="nav-collapse-01">
                        <ul class="nav">
                            <li class="mode_IdleMode">
                                <a href="" ng-click="menuClick('IdleMode');">
                                    Idle {{testing}}
                                </a>
                            </li>

                            <?php

                            foreach($mode_names as $name)
                            {
                                if($name != "IdleMode")
                                {
                                    $display = str_ireplace('Mode', '', $name);
                                    ?>

                                    <li class="mode_<?php echo $name;?>">
                                        <a href="" ng-click="menuClick('<?php echo $name; ?>');">
                                            <?php echo $display; ?>
                                        </a>
                                    </li>

                                    <?php
                                }

                            }

                            ?>
                        </ul>
                    </div><!--/.nav -->
                </div>
            </div>
        </div>

    </div>
</div>
<footer>
    <p class="palette palette-midnight-blue">By Justin Carmony - MIT License</p>
</footer>
<!-- /.container -->


<!-- Load JS here for greater good =============================-->
<script src="/js/jquery-1.8.3.min.js"></script>
<script src="/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="/js/jquery.ui.touch-punch.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrap-select.js"></script>
<script src="/js/bootstrap-switch.js"></script>
<script src="/js/flatui-checkbox.js"></script>
<script src="/js/flatui-radio.js"></script>
<script src="/js/jquery.tagsinput.js"></script>
<script src="/js/jquery.placeholder.js"></script>

<!-- Angular JS App -->
<script src="/js/app/app.js"></script>

</body>
</html>
